# https://github.com/joaopalmeiro/flake8-import-conventions/blob/main/.github/workflows/release.yml
# https://python-poetry.org/docs/cli/#install

name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.7"

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.3.2
          poetry --version
      - name: Create virtual environment
        run: |
          poetry install --without dev
          poetry env info
      - name: Build and publish to PyPI
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
          poetry publish --build --no-interaction
